spring:
  output:
    ansi:
      enabled: ALWAYS

  #    initialization-mode: always

  config:
    use-legacy-processing: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
