
spring:
  output:
    ansi:
      enabled: ALWAYS

  h2:
    console:
      enabled: true
      path: /h2
#    url: jdbc:h2:mem:test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buildTest?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: loginSQL@2
  #    initialization-mode: always

  config:
    use-legacy-processing: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        color-codes: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
