spring:
  output:
    ansi:
      enabled: ALWAYS

  #    initialization-mode: always

  config:
    use-legacy-processing: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        color-codes: false
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

# Spring Security
jwt:
  key: seb4312431243124312v4312431243124312
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420